-- Melhorias no perfil da empresa
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cep VARCHAR(10);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS endereco_rua VARCHAR(255);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS endereco_numero VARCHAR(20);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS endereco_bairro VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS endereco_cidade VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS endereco_uf VARCHAR(2);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS assinatura_path TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cor_tema VARCHAR(7) DEFAULT '#2c5aa0';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS logo_backup_path TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS logo_backup_date TIMESTAMP;